pipeline:
  test:
    image: node
    environment:
      NODE_PATH: src
    commands:
      - npm install --quiet
      - npm run build
    when:
      branch: master
      event: pull_request

  publish-staging:
    image: plugins/docker
    repo: devheavenci/frontend
    tags: "${DRONE_COMMIT_SHA:0:8}"
    build_args:
      - API_ENDPOINT=https://staging.devheaven.nl/api
      - HEALTH_ENDPOINT=https://svc.staging.devheaven.nl
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

  publish-production:
    image: plugins/docker
    repo: devheavenci/frontend
    tags: "${DRONE_TAG##v}"
    build_args:
      - API_ENDPOINT=https://devheaven.nl/api
      - HEALTH_ENDPOINT=https://svc.devheaven.nl
    secrets: [ docker_username, docker_password ]
    when:
      event: tag

  deploy-staging:
    image: quay.io/honestbee/drone-kubernetes
    namespace: staging
    deployment: frontend-deployment
    repo: devheavenci/frontend
    container: frontend
    tag: "${DRONE_COMMIT_SHA:0:8}"
    secrets: [ kubernetes_server, kubernetes_token, kubernetes_cert ]
    when:
      branch: master
      event: push

  deploy-production:
    image: quay.io/honestbee/drone-kubernetes
    namespace: production
    deployment: frontend-deployment
    repo: devheavenci/frontend
    container: frontend
    tag: "${DRONE_TAG##v}"
    secrets: [ kubernetes_server, kubernetes_token, kubernetes_cert ]
    when:
      event: tag

branches: master