pipeline:
  test:
    image: node
    commands:
      - npm install
      - npm run build
    when:
      branch: [ master ]
      event: [ push, pull_request ]

  publish:
    image: plugins/docker
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    email: devheavenplatform@gmail.com
    repo: devheaven/frontend
    tag: ${DRONE_BUILD_NUMBER}
    file: Dockerfile
    when:
      branch: [ master ]
      event: [ push ]
