pipeline:
  test:
    image: node
    environment:
      NODE_PATH: src
    commands:
      - npm install --quiet
      - npm run build
    when:
      branch: master
      event: pull_request

  code-analysis:
    image: ypcloud/sonar-runner
    host: "https://sonar.devheaven.nl"
    sources: "./src"
    profile: "Sonar way React"
    secrets: [ sonar_login, sonar_password ]
    when:
      branch: master
      event: pull_request

  publish-staging:
    image: plugins/docker
    repo: devheavenci/frontend
    tags: "${DRONE_COMMIT_SHA:0:8}"
    build_args:
      - ENV_NAME=staging
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

  publish-production:
    image: plugins/docker
    repo: devheavenci/frontend
    tags: "${DRONE_TAG##v}"
    build_args:
      - ENV_NAME=production
    secrets: [ docker_username, docker_password ]
    when:
      event: tag

  deploy-staging:
    image: quay.io/honestbee/drone-kubernetes
    namespace: staging
    deployment: frontend-deployment
    repo: devheavenci/frontend
    container: frontend
    tag: "${DRONE_COMMIT_SHA:0:8}"
    secrets: [ kubernetes_server, kubernetes_token, kubernetes_cert ]
    when:
      branch: master
      event: push

  deploy-production:
    image: quay.io/honestbee/drone-kubernetes
    namespace: production
    deployment: frontend-deployment
    repo: devheavenci/frontend
    container: frontend
    tag: "${DRONE_TAG##v}"
    secrets: [ kubernetes_server, kubernetes_token, kubernetes_cert ]
    when:
      event: tag

branches: master